services:
  # Server - Web Service (Node.js)
  - type: web
    name: werewolf-mafia-server
    env: node
    buildCommand: corepack enable && corepack prepare pnpm@10.11.1 --activate && pnpm install --frozen-lockfile
    startCommand: cd apps/server && pnpm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: HOST_URL
        fromService:
          type: static
          name: werewolf-mafia-host
          property: url
      - key: PLAYER_URL
        fromService:
          type: static
          name: werewolf-mafia-player
          property: url

  # Host App - Static Site (React/Vite)
  - type: static
    name: werewolf-mafia-host
    buildCommand: corepack enable && corepack prepare pnpm@10.11.1 --activate && pnpm install --frozen-lockfile && pnpm --filter @werewolf-mafia/host build
    publishPath: apps/host/dist
    envVars:
      - key: VITE_SERVER_URL
        fromService:
          type: web
          name: werewolf-mafia-server
          property: url

  # Player App - Static Site (React/Vite)  
  - type: static
    name: werewolf-mafia-player
    buildCommand: corepack enable && corepack prepare pnpm@10.11.1 --activate && pnpm install --frozen-lockfile && pnpm --filter @werewolf-mafia/player build
    publishPath: apps/player/dist
    envVars:
      - key: VITE_SERVER_URL
        fromService:
          type: web
          name: werewolf-mafia-server
          property: url 