# Render.com configuration for Werewolf Mafia
services:
  # Server - Web Service (Node.js)
  - type: web
    name: werewolf-mafia-server
    runtime: node
    plan: pro
    buildCommand: corepack enable && corepack prepare pnpm@10.11.1 --activate && pnpm install
    startCommand: cd apps/server && node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: HOST_URL
        value: https://werewolf-mafia-host.onrender.com
      - key: PLAYER_URL
        value: https://werewolf-mafia-player.onrender.com
      - key: PORT
        value: 10000

  # Host App (React/Vite Web Service)
  - type: web
    name: werewolf-mafia-host
    runtime: node
    plan: pro
    buildCommand: corepack enable && corepack prepare pnpm@10.11.1 --activate && pnpm install && cd apps/host && pnpm install && pnpm build
    startCommand: cd apps/host && node server.js
    envVars:
      - key: VITE_SERVER_URL
        value: https://werewolf-mafia-server.onrender.com
      - key: PORT
        value: 10000

  # Player App (React/Vite Web Service)
  - type: web
    name: werewolf-mafia-player
    runtime: node
    plan: pro
    buildCommand: corepack enable && corepack prepare pnpm@10.11.1 --activate && pnpm install && cd apps/player && pnpm install && pnpm build
    startCommand: cd apps/player && node server.js
    envVars:
      - key: VITE_SERVER_URL
        value: https://werewolf-mafia-server.onrender.com
      - key: PORT
        value: 10000 