services:
  # Server - Web Service (Node.js)
  - type: web
    name: werewolf-mafia-server
    runtime: node
    plan: free
    buildCommand: corepack enable && corepack prepare pnpm@10.11.1 --activate && pnpm install --frozen-lockfile
    startCommand: cd apps/server && pnpm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: HOST_URL
        fromService:
          type: web
          name: werewolf-mafia-host
          property: host
      - key: PLAYER_URL
        fromService:
          type: web
          name: werewolf-mafia-player
          property: host

  # Host App (React/Vite Web Service)
  - type: web
    name: werewolf-mafia-host
    runtime: node
    plan: free
    buildCommand: corepack enable && corepack prepare pnpm@10.11.1 --activate && pnpm install --frozen-lockfile && pnpm --filter @werewolf-mafia/host build
    startCommand: cd apps/host && node server.js
    envVars:
      - key: VITE_SERVER_URL
        fromService:
          type: web
          name: werewolf-mafia-server
          property: hostport
    dependsOn:
      - werewolf-mafia-server

  # Player App (React/Vite Web Service)
  - type: web
    name: werewolf-mafia-player
    runtime: node
    plan: free
    buildCommand: corepack enable && corepack prepare pnpm@10.11.1 --activate && pnpm install --frozen-lockfile && pnpm --filter @werewolf-mafia/player build
    startCommand: cd apps/player && node server.js
    envVars:
      - key: VITE_SERVER_URL
        fromService:
          type: web
          name: werewolf-mafia-server
          property: hostport
    dependsOn:
      - werewolf-mafia-server 